#!/bin/zsh
# This hook is sourced after every virtualenv is deactivated.
if [ "$virenv" = "manifold" ]; then
    echo "De-activating minikube docker env..."
    unset DOCKER_TLS_VERIFY
    unset DOCKER_HOST
    unset DOCKER_CERT_PATH
    unset DOCKER_API_VERSION
fi
